REGION = "eu-west-1"

ENV = "dev"

VPC_CIDR                        = "10.1.0.0/16"

SUBNET_TZ_FARM_CIDR             = "10.1.0.0/24"
SUBNET_TZ_PUBLIC_PROXY_CIDR     = "10.1.1.0/24"
SUBNET_TZ_PRIVATE_PROXY_CIDR    = "10.1.2.0/24"
SUBNET_TZ_PRIVATE_DATABASE_CIDR = "10.1.3.0/24"

INSTANCE_TYPE = "i3.large"
KEY_PAIR_NAME = "adbo"

PROXY_DOCKER_IMAGE_NAME = ""
PROXY_DOCKER_IMAGE_VERSION = ""

PROXY_PORT = 8001
PROXY_CPU = 1024
PROXY_MEMORY = 2

PROXY_DESIRED_COUNT = 1

PROXY_CONFIGURATION_FILE = "infra"